spring:
  datasource:
    url: jdbc:sqlserver://petshop-sql-db-server.database.windows.net:1433;encrypt=true;trustServerCertificate=false;loginTimeout=30;database=db_petshop;
    username: "SystemAdministrator"
    password: "P4$$w0rD"
    hikari:
      read-only: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    web: INFO
    root: WARN

debug: true
