server:
  port: 8080
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: petservice
  profiles:
    active: prod # local
  jackson:
    date-format: "dd/MM/yyyy"
    serialization:
      write-dates-as-timestamps: false
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    display-request-duration: true
    tags-sorter: alpha

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

debug: true

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "openapi, swagger-ui, health, info, metrics"
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: DEBUG
    root: INFO
  pattern:
    date-format: "yyyy-MM-dd HH:mm:ss,SSS"
    console: "%d{date-format} [%thread] %-5level %logger{36} - %msg%n"
