spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_petshop?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: "root"
    password: "root123"
    hikari:
      read-only: false
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
